import React, {Component} from "react";
import {View, Text, StyleSheet,TouchableOpacity } from 'react-native';
import { ScrollView } from "react-native-gesture-handler";
import Cabecalho from '../../componentes/Cabecalho';




export default function TermoAbertura({navigation}){
 


        return(
            <View style={style.container}>
                <View>
                    <Cabecalho />
                </View>

                <View style={style.body}>

                        <View style={{alignItems:'center', width:'100%', marginTop:'2%'}}>
                            <Text style={{color:'#011e50', fontSize:16, fontWeight:'bold'}}> Termo de Abertura de Conta</Text>
                        </View>

                            <ScrollView style={{width:'95%', marginBottom:10,marginTop:15, borderRadius:15, borderWidth:1, borderColor:'#d3d3d3'}}>
                                
                                    <Text style={{fontWeight:'bold', fontSize:14, textAlign:'center', marginTop:10}}> TERMO DE ABERTURA DE CONTA DE PAGAMENTO  </Text>
                                    <Text style={{fontWeight:'bold', fontSize:14, textAlign:'center'}}> SISTEMA TRUCKER PAY  </Text>
                                    <Text>Por este instrumento, a pessoa física ou jurídica identificada e qualificada no Cadastro, que é parte integrante deste Termo (“USUÁRIO”); e MAN LATIN AMERICA INDÚSTRIA E COMÉRCIO DE VEÍCULOS LTDA., sociedade empresária limitada, inscrita no CNPJ sob o nº 06.020.318/00001-10, com sede na Rua Volkswagen, nº 291, 7º, 8º e 9º andares, bairro Jabaquara, cidade de São Paulo, estado de São Paulo, CEP 04344-901 (“MAN”); têm entre si justo e acordado este Termo de Abertura de Conta de Pagamento (“Termo”), nos termos e condições abaixo.</Text>
                                    <Text>Os serviços relacionados com a gestão e custódia de recursos serão prestados pela Login Tecnologia e Pagamentos Ltda., inscrita no CNPJ sob o nº 24.867.237/0001-32, com sede na Alameda Araguaia, 2.044, bloco 1, conj. 707, bairro Alphaville Industrial, cidade de Barueri, estado de São Paulo, CEP 06455-906, na qualidade de instituição de pagamento (“Instituição de Pagamento”).</Text>
                                    <Text style={{fontWeight:'bold'}}> Ao aceitar eletronicamente este Termo, com a marcação da caixa de diálogo “Li e concordo com o Termos de Abertura da Conta de Pagamento”, o USUÁRIO estará automaticamente aderindo e concordando com os termos e condições deste Termo e da Política de Privacidade, assim como do Regulamento sobre o programa de Cashback.</Text>
                                    <Text style={{fontWeight:'bold'}}>Este Termo regula os Serviços que serão prestados para a realização de Transações pelo USUÁRIO, para que possa receber e realizar pagamentos por meio das Funcionalidades disponíveis na Plataforma.</Text>
                                    <Text style={{fontWeight:'bold'}}>As condições deste Termo poderão ser periodicamente alteradas, mediante comunicação prévia ao USUÁRIO. Caso não concorde com as modificações, o USUÁRIO deverá encerrar sua Conta de Pagamento; sendo que a realização de novas Transações será interpretada como a aceitação às alterações realizadas.</Text>
                                    <Text style={{fontWeight:'bold'}}>Qualquer dúvida em relação a este Termo ou sobre a realização de Transações no Sistema Trucker Pay, poderá ser dirimida por meio dos canais de atendimento disponibilizados na Plataforma.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>1. Definições</Text>
                                    <Text>1.1.	As palavras e expressões indicadas neste Termo pela primeira letra maiúscula terão as definições abaixo:</Text>
                                    <Text>“Banco Volkswagen”: Banco Volkswagen S.A., instituição financeira inscrita no CNPJ sob o nº 59.109.165/0001-49, com sede na Rua Volkswagen, nº 291, bairro Jabaquara, cidade de São Paulo, estado de São Paulo, CEP 04344-901.</Text>
                                    <Text>“Cadastro”: formulário preenchido pelo USUÁRIO na Plataforma, contendo seus dados pessoais e demais informações necessárias para credenciamento ao Sistema Trucker Pay.</Text>
                                    <Text>“Cashback”: programa de benefícios, pelo qual o USUÁRIO recebe de volta parte do valor pago em determinadas Transações, observadas as condições previstas no Regulamento aplicável.</Text>
                                    <Text>“Conta de Pagamento”: conta de pagamento de titularidade do USUÁRIO, cujos recursos serão geridos e custodiados pela Instituição de Pagamento, e na qual serão feitos os lançamentos de débitos e créditos decorrentes das Transações realizadas no Sistema Trucker Pay.</Text>
                                    <Text>“Disputa”: procedimento de análise do pedido de cancelamento ou estorno de uma Transação, observados os limites previstos neste Termo.</Text>
                                    <Text>“Funcionalidades”: ferramentas tecnológicas disponibilizadas na Plataforma, para a realização de Transações e utilização de outros serviços disponibilizados ao USUÁRIO.</Text>
                                    <Text>“Plataforma”: site na internet disponível em www.truckerpay.com.br, e aplicativo para dispositivos móveis, que, conforme aplicável, será disponibilizado ao USUÁRIO para a utilização das Funcionalidades e realização de Transações.</Text>
                                    <Text>“Política de Privacidade”: política disponível em www.truckerpay.com.br/xxxxxxx, e que é integrante deste Termo, a qual dispõe sobre a coleta, utilização, armazenamento, tratamento, compartilhamento, proteção e eliminação das informações do USUÁRIO, em decorrência da utilização do Sistema Trucker Pay.</Text>
                                    <Text>“Serviços Financeiros”: serviços financeiros que poderão estar disponíveis ao USUÁRIO na Plataforma, e que não se confundem com os serviços decorrentes do Sistema Trucker Pay.</Text>
                                    <Text>“Sistema Trucker Pay”: serviços para a abertura de Conta de Pagamento e realização de Transações pelo USUÁRIO, de acordo com as condições previstas neste Termo.</Text>
                                    <Text>“Tarifa”: remuneração devida à Instituição de Pagamento, em razão da realização das Transações pelo Sistema Trucker Pay.</Text>
                                    <Text>“Termo”: estes Termos e Condições para Abertura de Conta de Pagamento, que consiste num contrato eletrônico, disponível para consulta, a qualquer tempo, em www.truckerpay.com.br/xxxxxxx.</Text>
                                    <Text>“Transação”: operação em que o USUÁRIO realiza a movimentação de sua Conta de Pagamento, para a realização e o recebimento de pagamentos e transferências por meio do Sistema Trucker Pay.</Text>
                                    <Text>“Transação Pós-Paga”: Transação pela qual os recursos são depositados pelo USUÁRIO na Conta de Pagamento para a quitação de débitos decorrentes de transferências e pagamentos já realizados.</Text>
                                    <Text>“Transação Pré-Paga”: Transação pela qual o USUÁRIO poderá realizar transferências e pagamentos, mediante o aporte prévio de recursos na Conta de Pagamento.</Text>
                                    <Text>“USUÁRIO”: motoristas, transportadoras, estabelecimentos comerciais ou outras pessoas físicas ou jurídicas que, ao aderirem a este Termo, estão habilitadas a realizar Transações no Sistema Trucker Pay e utilizar as Funcionalidades disponíveis na Plataforma.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>2.  Sistema Trucker Pay</Text>
                                    <Text>2.1.	    Este Termo regula a prestação de serviços de tecnologia pela MAN, individualmente ou por intermédio da Instituição de Pagamento, para: (i) credenciamento do USUÁRIO ao Sistema Trucker Pay; (ii) criação de Conta de Pagamento, habilitando o USUÁRIO a realizar Transações; e (iii) gestão e custódia dos recursos mantidos na Conta de Pagamento de titularidade do USUÁRIO.</Text>
                                    <Text>2.1.1.    O credenciamento ao Sistema Trucker Pay habilitará o USUÁRIO para a realização de Transações Pré-Pagas, para que sejam efetuados pagamentos e transferências, após o aporte prévio de recursos.</Text>
                                    <Text>2.1.2.	Caso seja concedido ao USUÁRIO um Limite de Crédito para a realização de Transações Pós-Pagas, aplicam-se as condições previstas no “Anexo I – Transações Pós-Pagas”.</Text>
                                    <Text>2.1.3.	Ainda, os serviços prestados em razão deste Termo incluem o fornecimento de tecnologia para que o USUÁRIO possa contratar Serviços Financeiros perante o Banco Volkswagen.</Text>
                                    <Text>2.1.4.	Para os USUÁRIOS que, na qualidade de estabelecimentos comerciais, irão receber pagamentos em razão da comercialização de produtos e/ou serviços a outros USUÁRIOS credenciados no Sistema Trucker Pay, aplicam-se as condições previstas no “Anexo II – Credenciamento de Estabelecimentos”.</Text>
                                    <Text>2.2.	    Por meio da Plataforma, o USUÁRIO poderá utilizar as Funcionalidades para: (i) carregamento, movimentação e resgate dos recursos de sua Conta de Pagamento; (ii) consulta ao saldo da Conta de Pagamento e ao extrato das Transações; e (iii) contratação dos Serviços Financeiros; dentre outras funcionalidades disponíveis. </Text>
                                    <Text>2.2.1.	As Funcionalidades disponíveis na Plataforma poderão, a qualquer momento e sem necessidade de aviso prévio, ser excluídas, alteradas ou modificadas.</Text>
                                    <Text>2.3.	    Os serviços decorrentes do Sistema Trucker Pay serão prestados de forma remota, mediante a disponibilização das Funcionalidades existentes na Plataforma. </Text>
                                    <Text>2.3.1.	As Funcionalidades disponibilizadas na Plataforma irão variar de acordo com cada categoria de USUÁRIO.</Text>
                                    <Text>2.4.	    A MAN e a Instituição de Pagamento, sob sua exclusiva responsabilidade, poderão subcontratar terceiros ou realizar parcerias para a prestação dos serviços que integram o Sistema Trucker Pay</Text>
                                    <Text style={{fontWeight:'bold'}}>2.5.	    Em razão deste Termo, não se garante a ininterrupção e a velocidade do Sistema Trucker Pay e/ou da Plataforma, que poderão apresentar indisponibilidade, lentidão e erros de processamento, inclusive em casos de manutenção preventiva ou corretiva, falha de operação, erro de sistema, falhas de outros prestadores de serviços e eventos casos fortuitos ou força maior.</Text>
                                    <Text style={{fontWeight:'bold'}}>2.5.1.	Ainda, a MAN e a Instituição de Pagamento não serão responsáveis pela: (i) intermitência ou indisponibilidade de conexão à internet adotada pelo USUÁRIO; (ii) incapacidade técnica do dispositivo móvel ou sistema operacional do USUÁRIO; (iii) indisponibilidade da Plataforma na loja de aplicativos ou navegador de internet utilizados pelo USUÁRIO; e/ou (iv) atividades de pessoas não autorizadas a utilizar o Sistema Trucker Pay ou a Plataforma.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>3. 	Credenciamento do USUÁRIO</Text>
                                    <Text>3.1.	    O credenciamento ao Sistema Trucker Pay será realizado pela adesão do USUÁRIO a este Termo, que se efetivará pelo: (i) preenchimento do Cadastro; e (ii) aceite eletrônico expressamente manifestado na Plataforma.</Text>
                                    <Text>3.2.	    Para utilização do Sistema Trucker Pay, o USUÁRIO deverá obrigatoriamente preencher o Cadastro, fornecendo seus dados pessoais e informações que venham a ser solicitados na Plataforma, podendo ser, conforme solicitado:</Text>
                                    <Text>(a)	Para pessoa física, deverão ser fornecidos: nome completo, estado civil, e-mail de contato, número de inscrição no CPF válido e ativo, número da Carteira Nacional de Habilitação (CNH), Cédula de Identidade (RG) e comprovante de residência; e</Text>
                                    <Text>(b)	Para pessoa jurídica, deverão ser fornecidos: razão social ou denominação, nome fantasia, atividade, endereço completo, e-mail e telefone de contato, número de inscrição no CNPJ válido e ativo, e as informações acima indicadas para seus representantes, mandatários ou prepostos autorizados.</Text>
                                    <Text>3.2.1.	Os dados e informações de cada USUÁRIO poderão variar de acordo com os serviços que forem prestados, conforme exigido no momento do Cadastro.</Text>
                                    <Text>3.2.2.	A MAN e a Instituição de Pagamento poderão limitar a utilização do Sistema Trucker Pay, de acordo com o valor e a quantidade de Transações.</Text>
                                    <Text>3.2.3.	Sempre que necessário, inclusive para possibilitar a utilização do Sistema Trucker Pay para realização de Transações em valor e quantidade superior aos limites estabelecidos, poderá ser solicitado ao USUÁRIO que forneça informações complementares àquelas indicadas no Cadastro, bem como cópias de documentos para averiguação da veracidade das informações prestadas.</Text>
                                    <Text>3.2.4.	Na hipótese de se verificar dados incorretos ou inverídicos fornecidos pelo USUÁRIO ou, ainda, caso o USUÁRIO se recuse ou se omita a enviar as informações e documentos solicitados, o acesso ao Sistema Trucker Pay será temporariamente bloqueado, impossibilitando a utilização das Funcionalidades até que haja a regularização.</Text>
                                    <Text>3.2.5.	O USUÁRIO autoriza a realização de pesquisas, em base de dados públicas ou privadas, com a finalidade de verificar a veracidade dos dados e informações indicadas no Cadastro.</Text>
                                    <Text>3.3.	    O USUÁRIO se responsabiliza civil e criminalmente pela veracidade das informações prestadas, inclusive perante terceiros; obrigando-se, ainda, a manter seus dados atualizados, mediante alteração na Plataforma.</Text>
                                    <Text>3.3.1.	A MAN e a Instituição de Pagamento não serão responsáveis por erros ou pela inexecução dos serviços que integram o Sistema Trucker Pay, caso o USUÁRIO preste informações inexatas, inverídicas ou desatualizadas.</Text>
                                    <Text>3.4.	    O USUÁRIO, quando do preenchimento do Cadastro, deverá cadastrar login e senha para utilização das Funcionalidades disponíveis na Plataforma.</Text>
                                    <Text>3.4.1.	O uso do login e senha são de uso pessoal, exclusivo e intransferível pelo USUÁRIO, que deverá mantê-los confidenciais e não permitir seu acesso por terceiros.</Text>
                                    <Text>3.4.2.	O USUÁRIO, caso se trate de pessoa jurídica, se compromete a somente dar acesso ao login e senha para seus representantes legais, sócios, administradores e/ou prepostos com poderes para celebrar negócios jurídicos em seu nome; sendo responsável, perante à MAN, outros USUÁRIOS, a Instituição de Pagamento, o Banco Volkswagen e terceiros, por todos os atos e negócios realizados por meio da utilização do Sistema Trucker Pay.</Text>
                                    <Text>3.4.3.	Ainda, o USUÁRIO deverá informar um e-mail válido para comunicação com a MAN e a Instituição de Pagamento; comprometendo-se a mantê-lo atualizado, mediante alteração na Plataforma. Qualquer notificação enviada por e-mail ou pela Plataforma será considerada válida e eficaz entre as Partes.</Text>
                                    <Text>3.5.	    Para utilizar os serviços, o USUÁRIO, dentre outras obrigações previstas neste Termo, deve ser: (i) pessoa física, maior de 18 (dezoito) anos e com inscrição válida e regular perante a Receita Federal do Brasil; ou (ii) pessoa jurídica devidamente constituída, com sede ou escritório no Brasil e possuir inscrição válida e regular perante a Receita Federal do Brasil.</Text>
                                    <Text>3.5.1.	Em razão da natureza dos serviços prestados, a MAN e a Instituição de Pagamento não possuem condições de verificar a capacidade civil e regularidade do USUÁRIO; de forma que não responderão por quaisquer prejuízos que venham a ser causados em razão da inobservância das condições acima indicadas.</Text>
                                    <Text>3.6.	    É vedada a utilização do Sistema Trucker Pay e a realização das Transações para a celebração de negócios: (i) considerados ilícitos, nos termos da legislação vigente; (ii) que importem em violação ao Sistema Financeiro Nacional e às normas do Banco Central do Brasil; (iii) considerados como crimes financeiros, com o intuito de lavagem de dinheiro, financiamento ao terrorismo e corrupção, dentre outros crimes correlatos, de acordo com as normas do Conselho de Controle de Atividades Financeiras - COAF; (iv) que não representem um negócio jurídico regular e tenham por intenção a prática de fraudes; ou (v) que, de qualquer modo, venham a causar prejuízos à MAN, à Instituição de Pagamento, ao Banco Volkswagen, aos demais USUÁRIOS ou quaisquer terceiros.</Text>
                                    <Text>3.7.	    As Transações com indícios ou suspeitas de fraude estarão sujeitas ao não processamento ou ao cancelamento, ainda que realizadas de forma não conivente pelo USUÁRIO.</Text>
                                    <Text>3.8.	    A Instituição de Pagamento poderá suspender o acesso às Funcionalidades e deixar de realizar as Transações pelo Sistema Trucker Pay sempre que identificar ou entender que a atividade do USUÁRIO ou natureza das Transações viola qualquer dispositivo deste Termo ou da legislação vigente; podendo sujeitar o USUÁRIO ao cancelamento do seu credenciamento e sua exclusão imediata do Sistema Trucker Pay, independentemente de qualquer aviso ou notificação prévia, não gerando ao USUÁRIO qualquer tipo de indenização ou ressarcimento.</Text>
                                    <Text>3.9.	    Para o USUÁRIO que pretenda receber pagamentos em razão da comercialização de produtos e/ou serviços, aplicam-se, ainda, a disposições previstas no “Anexo II – Credenciamento de Estabelecimentos"</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>4. 	    Realização de Transações</Text>
                                    <Text>4.1.	    Ao realizar o Cadastro na Plataforma e aderir a este Termo, o USUÁRIO concorda com a abertura de Conta de Pagamento Pré-Paga, de sua exclusiva titularidade, a qual poderá ser movimentada por meio das Funcionalidades.</Text>
                                    <Text>4.1.1.	O simples preenchimento do Cadastro não implica na abertura automática da Conta de Pagamento, o que somente ocorrerá após: (i) o aporte prévio de recursos por um dos meios disponíveis; e (ii) a realização de uma Transação no Sistema Trucker Pay.</Text>
                                    <Text>4.1.2.	A realização de Transações Pós-Pagas dependerá da aprovação prévia e expressa pela MAN e pela Instituição de Pagamento; aplicando-se, nesse caso, as condições previstas no “Anexo I – Transações Pós-Pagas”.</Text>
                                    <Text>4.2.	    O carregamento da Conta de Pagamento se dará por um dos meios disponíveis no Sistema Trucker Pay, de livre escolha do USUÁRIO, dentre os quais: </Text>
                                    <Text>(a)	Pagamento de boleto bancário, pelo USUÁRIO, com identificação única que permita o carregamento do valor pago na Conta de Pagamento;</Text>
                                    <Text>(b)	Transferência bancária realizada pelo próprio USUÁRIO - ou terceiros em favor do USUÁRIO -, mediante operações de TEF, DOC ou TED;</Text>
                                    <Text>(c)	Transferências realizadas por outros USUÁRIOS no âmbito do Sistema Trucker Pay, mediante a utilização das Funcionalidades ou QR Code; </Text>
                                    <Text>(d)	Transferência de recursos em razão do Cashback; e</Text>
                                    <Text>(e) 	Pagamentos instantâneos pelo Arranjo PIX.</Text>
                                    <Text>4.2.1.	No momento da adesão do USUÁRIO a este Termo, uma ou mais formas de carregamento poderão não estar disponíveis, e poderão ser incluídas posteriormente, mediante disponibilização das Funcionalidades na Plataforma e comunicação ao USUÁRIO.</Text>
                                    <Text>4.2.2.	Com o carregamento da Conta de Pagamento, por uma das modalidades existentes, os recursos estarão disponíveis no Sistema Trucker Pay em até 02 (dois) dias úteis contados do efetivo recebimento dos recursos pela Instituição de Pagamento; sendo possível ao USUÁRIO, a partir de então, realizar Transações Pré-Pagas.</Text>
                                    <Text>4.2.3.	O USUÁRIO declara-se ciente de que os boletos bancários emitidos irão indicar como beneficiário a Instituição de Pagamento, que, após o recebimento dos recursos, irá realizar o carregamento da Conta de Pagamento.</Text>
                                    <Text>4.3.	    Os recursos mantidos na Conta de Pagamento poderão ser utilizados para transferências e pagamentos, por um dos meios disponíveis no Sistema Trucker Pay, dentre os quais:</Text>
                                    <Text>(a) 	Pagamentos e transferências para outros USUÁRIOS credenciados no Sistema Trucker Pay, mediante a utilização das Funcionalidades ou QR Code;</Text>
                                    <Text>(b) 	Pagamento de débitos do USUÁRIO perante o Banco Volkswagen;</Text>
                                    <Text>(c) 	Pagamento de boletos bancários e contas de consumo;</Text>
                                    <Text>(d) 	Realização de recarga de serviços pré-pagos, incluindo, mas não se limitando a telefonia móvel, transporte público, lojas de aplicativos, dentre outras;</Text>
                                    <Text>(e)	Resgate de recursos, mediante transferência para a conta bancária de titularidade do USUÁRIO ou de terceiros por ele indicados; e </Text>
                                    <Text>(f)	Pagamentos instantâneos pelo Arranjo PIX.</Text>
                                    <Text>4.3.1.	No momento da adesão do USUÁRIO a este Termo, uma ou mais formas de transferência e pagamento poderão não estar disponíveis, e poderão ser incluídas posteriormente, mediante disponibilização das Funcionalidades na Plataforma e comunicação ao USUÁRIO.</Text>
                                    <Text>4.3.2.	O resgate de recursos será realizado em até 03 (três) dias úteis contados da realização da Transação Pré-Paga; podendo ocorrer em prazo inferior, conforme informado na Plataforma. </Text>
                                    <Text>4.3.4.	As Transações Pré-Pagas deixarão de ser acatadas pela Instituição de Pagamento quando: (i) não houver recursos suficientes na Conta de Pagamento; (ii) o USUÁRIO deixar de fornecer as informações suficientes ou fornecer informações incorretas para realização da Transação; e/ou (iii) houver indícios de fraude ou suspeita ou ato ilícito, de acordo com os termos previstos neste Termo e na legislação vigente. </Text>
                                    <Text>4.4.	    A MAN e a Instituição de Pagamento poderão, a qualquer momento, estipular outras formas de carregamento, transferência e pagamento, mediante disponibilidade por meio das Funcionalidades.</Text>
                                    <Text>4.5.	    A Instituição de Pagamento poderá determinar limites de valor mínimo e máximo para o carregamento das Contas de Pagamento e para a realização das Transações Pré-Pagas ou Pós-Pagas; o que poderá variar de acordo com as informações de Cadastro do USUÁRIO, o tipo de Transação, ou outro critério por elas definido. .</Text> 
                                    <Text>4.6.	    Os recursos creditados na Conta de Pagamento do USUÁRIO serão mantidos em conta bancária de titularidade da Instituição de Pagamento, em instituição financeira de primeira linha, e, nos termos do art. 12 da Lei 12.865/2013, (i) constituem patrimônio separado, que não se confunde com o da Instituição de Pagamento; (ii) não respondem direta ou indiretamente por nenhuma obrigação da Instituição de Pagamento, nem podem ser objeto de arresto, sequestro, busca e apreensão ou qualquer outro ato de constrição judicial em função de débitos de responsabilidade da Instituição de Pagamento; (iii) não podem ser dados em garantia de débitos assumidos pela Instituição de Pagamento; e (iv) não compõem o ativo da Instituição de Pagamento, para efeito de falência ou liquidação judicial ou extrajudicial. .</Text>
                                    <Text>4.7.	    Os recursos mantidos na Conta de Pagamento, salvo se expressamente pactuado de modo diverso, não sofrerão qualquer tipo de acréscimo, tais como correção monetária e juros; e nem haverá o pagamento de qualquer remuneração ao USUÁRIO, independentemente do período que ficarem depositados.</Text>
                                    <Text>4.8.	    Os valores depositados na Conta de Pagamento devem ser utilizados para pagamentos e transferências, sendo considerados pela Instituição de Pagamento como recursos em trânsito de titularidade do USUÁRIO.</Text>
                                    <Text>4.9.	    O USUÁRIO não poderá ceder ou onerar, a qualquer título, os direitos sobre os recursos depositados em sua Conta de Pagamento, sem a prévia e expressa autorização da MAN, sob pena de ineficácia da cessão. .</Text>
                                    <Text>4.10.	    O USUÁRIO terá acesso às Transações realizadas ou pendentes de pagamento pelo acesso ao extrato de sua Conta de Pagamento, podendo visualizar na Plataforma, o saldo e histórico das movimentações. A disponibilização do saldo e do extrato das movimentações caracteriza-se como prestação de contas, para todos os fins legais.</Text>
                                    <Text>4.10.1.	Apenas será disponibilizado o acesso às Transações realizadas a cada período mínimo de 12 (doze) meses, cabendo ao USUÁRIO o controle e arquivo, inclusive com a possibilidade de impressão do extrato disponibilizado na Plataforma.</Text>
                                    <Text>4.11.	    O USUÁRIO declara-se ciente de que os serviços previstos neste Termo se destinam tão somente a efetivar pagamentos e recebimentos em moeda nacional, bem como assegura que todos os recursos movimentados em sua Conta de Pagamento serão oriundos de fontes lícitas e declaradas, isentando a MAN, a Instituição de Pagamento e o Banco Volkswagen de qualquer responsabilidade.</Text>
                                    <Text>4.12.	    O USUÁRIO poderá ser elegível para participar de um programa de Cashback, pelo qual receberá parte do valor pago em determinadas Transações, mediante o carregamento de sua Conta de Pagamento. .</Text>
                                    <Text>4.12.1.	O valor, os critérios de elegibilidade e as condições relacionadas ao Cashback se encontram previstos em Regulamento específico disponível na Plataforma, e poderá ser aplicável para apenas alguns USUÁRIOS. .</Text>
                                    <Text>4.12.2.	O aceite a este Contrato enseja na adesão automática do USUÁRIO ao Regulamento aplicável ao Cashback, o qual poderá ser periodicamente alterado, mediante divulgação da nova versão na Plataforma. .</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>5. 	Regras de Disputa</Text>
                                    <Text>5.1.	    As reclamações e contestações decorrentes de quaisquer Transações realizadas no Sistema Trucker Pay deverão ser dirimidas diretamente entre os USUÁRIOS e os terceiros envolvidos.</Text> 
                                    <Text>5.1.1.	O USUÁRIO declara-se ciente e concorda que será integralmente responsável pela veracidade, precisão e conformidade das informações e valores relacionados com os negócios que deram origem Transações; respondendo, conforme aplicável, pela qualidade, quantidade, segurança, adequação, preço, prazo, entrega e garantia dos produtos ou serviços que deram origem às Transações. .</Text>
                                    <Text>5.1.2.	A MAN e a Instituição de Pagamento estão isentas de qualquer responsabilidade relacionada aos negócios celebrados entre os USUÁRIOS. .</Text>  
                                    <Text>5.1.3.	Não será possível o cancelamento ou abertura de Disputa para as Transações realizadas fora do âmbito do Sistema Trucker Pay, ou seja, antes do recebimento ou após o repasse de valores pela Instituição de Pagamento. .</Text>
                                    <Text>5.2.	    O USUÁRIO poderá iniciar o procedimento de Disputa apenas se a Transação: (i) tiver sido processada incorretamente, em razão de informações errôneas ou incompletas; (ii) for duplicata por erro de processamento; (iii) for recusada pelo destinatário dos recursos; ou (iv) houver suspeita de fraude. .</Text>
                                    <Text>5.2.1.	Verificada uma das hipóteses acima indicadas, o USUÁRIO poderá apresentar a contestação de uma Transação, para que seja iniciado o procedimento de Disputa, com a retenção do valor da Transação até a solução da Disputa. .</Text>
                                    <Text>5.3.	    A Disputa deverá ser aberta pelo USUÁRIO no prazo máximo de 10 (dez) dias contados da data de realização da Transação, diretamente na central de atendimento disponível na Plataforma; sendo certo que a abertura da Disputa não garante a restituição dos valores em discussão. .</Text>
                                    <Text>5.3.1.	O pedido de abertura de Disputa deverá ser devidamente fundamentado e acompanhado da documentação pertinente. .</Text> 
                                    <Text>5.3.2.	Com a abertura do procedimento de Disputa, será solicitado aos USUÁRIOS envolvidos, explicações e documentos que comprovam a realização do negócio que deu origem à Transação. .</Text> 
                                    <Text>5.3.3.	Caberá unicamente à Instituição de Pagamento, por critérios próprios, analisar a documentação e decidir sobre a Disputa, em até 30 (trinta) dias contados do envio das informações e documentos pelo último USUÁRIO comunicado.</Text>
                                    <Text>5.3.4.	Caso a contestação seja acolhida, haverá o estorno do valor respectivo da Conta de Pagamento do USUÁRIO que iniciou a Disputa. Se a contestação não for acolhida, a Transação realizada será mantida. .</Text>
                                    <Text>5.3.5.	Caso o USUÁRIO que solicitou a abertura da Disputa deixe de apresentar as informações e documentos solicitados, o procedimento será automaticamente encerrado, sem a necessidade de novo aviso. .</Text>
                                    <Text>5.3.6.	Enquanto o pedido de abertura de Disputa estiver pendente de solução, não será possível o pagamento antecipado da Transação respectiva. .</Text> 
                                    <Text>5.4. 	    Caso se identifique níveis excessivos de pedido de abertura de Disputa perante o USUÁRIO, a Instituição de Pagamento poderá, a seu exclusivo critério: (i) realizar a retenção, total ou parcialmente, dos valores existentes na Conta de Pagamento, como garantia para cobrir potenciais danos; e (ii) suspender o acesso do USUÁRIO à Plataforma. .</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>6. 	Hipóteses de Retenção e Compensação de Recursos</Text>
                                    <Text>6.1.	    O USUÁRIO reconhece e concorda que a Instituição de Pagamento, em conformidade com as disposições deste Termo e da legislação vigente, terá o direito de: (i) reter os valores mantidos na Conta de Pagamento do USUÁRIO para garantir, de forma integral, quaisquer pagamentos que sejam devidos ou para o resguardo contra riscos financeiros relacionados às obrigações do USUÁRIO; e (ii) compensar, com os valores mantidos na Conta de Pagamento, os débitos do USUÁRIO, de qualquer natureza.</Text>
                                    <Text>6.2.	    Será realizada a retenção e compensação dos valores, existentes ou futuros, mantidos na Conta de Pagamento do USUÁRIO, nas seguintes hipóteses:</Text>
                                    <Text>(a)	    Quando se verificar um alto nível de risco operacional, associado ao histórico de Transações realizadas pelo USUÁRIO;</Text>
                                    <Text>(b)	    Havendo indícios de irregularidade ou risco de cancelamento da Transação, em razão de denúncias, abertura de Disputa ou pelo uso inadequado do Sistema Trucker Pay;</Text> 
                                    <Text>(c)	    Nos casos em que se verificar a iliquidez, insolvência, pedido de recuperação judicial ou extrajudicial, pedido de falência, encerramento de atividades ou qualquer outra hipótese em que ficar caracterizada a dificuldade do USUÁRIO em cumprir suas obrigações contratuais e/ou legais;</Text> 
                                    <Text>(d)	    Sempre que houver o descumprimento das obrigações previstas neste Termo ou na legislação vigente; ou</Text>
                                    <Text>(e)	    Para cumprimento de ordens judiciais ou administrativas.</Text>
                                    <Text>6.3.	    Caso não haja saldo suficiente para arcar com o pagamento dos débitos devidos, o USUÁRIO será comunicado pela MAN para que proceda o carregamento imediato de sua Conta de Pagamento, sob pena de caracterização de sua mora, automaticamente e sem a necessidade de novo aviso ou qualquer formalidade.</Text> 
                                    <Text>6.3.1.    A ausência ou atraso no pagamento de quaisquer valores devidos pelo USUÁRIO, ensejará no pagamento de multa moratória de 2% (dois por cento), correção monetária pelo IGPM/FGV ou outro índice que vier a substituí-lo, e juros de 1% (um por cento) ao mês, a serem calculados sobre a quantia devida.</Text>
                                    <Text>6.3.2.	A inadimplência do USUÁRIO ensejará, ainda, na rescisão imediata deste Termo e na adoção das medidas legais para a cobrança do débito, inclusive a inclusão da dívida perante os órgãos de proteção ao crédito.</Text>
                                    <Text>6.4.	    O USUÁRIO terá o prazo de 90 (noventa) dias para apontar eventual divergência ou incorreção em relação aos valores lançados na Conta de Pagamento, a contar da realização da Transação, lançamento do débito ou compensação. Após esse prazo, o USUÁRIO não mais poderá reclamar sobre os lançamentos realizados, concedendo plena e definitiva quitação.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>7. 	Resgate de Recursos e Encerramento da Conta de Pagamento</Text>
                                    <Text>7.1.	    O USUÁRIO poderá, a qualquer momento, desde que possua saldo suficiente para arcar com a Tarifa de saque, as tarifas bancárias aplicáveis e o pagamento de eventuais débitos contraídos em razão deste Termo, efetuar o resgate integral dos recursos mantidos na Conta de Pagamento.</Text> 
                                    <Text>7.1.1.	O encerramento da Conta de Pagamento poderá ser realizado pela MAN e pela Instituição de Pagamento em caso de descumprimento das condições previstas neste Termo, e mediante a retenção e compensação de valores.</Text>
                                    <Text>7.2.	    O resgate de recursos será realizado a pedido do USUÁRIO, mediante o repasse do valor líquido e em moeda nacional, mediante transferência para a conta bancária por ele indicada.</Text>
                                    <Text>7.3.	    O USUÁRIO se responsabiliza pela exatidão dos dados informados sobre a conta bancária, de sua titularidade ou de terceiros; isentando a MAN e a Instituição de Pagamento de qualquer responsabilidade pelas transferências realizadas em razão de informações imprecisas ou inexatas</Text>
                                    <Text>7.3.1.	Caso não seja possível o resgate de recursos por irregularidade na conta bancária indicada, os respectivos valores permanecerão retidos e serão mantidos na Conta de Pagamento até que haja a regularização pelo USUÁRIO, sem a incidência de quaisquer ônus, penalidades ou encargos.</Text>
                                    <Text>7.4.	    Quando decorrente de falha técnica e/ou operacional no Sistema Trucker Pay ou no sistema bancário, a Instituição de Pagamento poderá, sem incorrer em qualquer ônus ou penalidade, exceder, em até 01 (um) dia útil, o prazo estabelecido para efetuar o resgate da Conta de Pagamento.</Text> 
                                    <Text>7.5.	    Na hipótese de a data prevista para o resgate de recursos ser considerada feriado ou em dia de não funcionamento bancário, o pagamento será realizado no 1º (primeiro) dia útil subsequente.</Text>
                                    <Text>7.6.	    A não utilização da Conta de Pagamento, definida como a ausência de qualquer utilização pelo prazo de 06 (seis) meses, ensejará na cobrança de Tarifa de inatividade, para o ressarcimento das despesas com sua manutenção, e que será descontada do saldo existente na Conta de Pagamento.</Text>
                                    <Text>7.7.	A partir do momento em que o USUÁRIO não possuir saldo em sua conta por mais de 30 (trinta) dias, sua Conta de Pagamento será automaticamente encerrada, após o envio de comunicação com 10 (dez) dias de antecedência.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>8. 	Tarifas</Text>
                                    <Text>8.1.	    Em contrapartida à prestação dos serviços de tecnologia que integram o Sistema Trucker Pay, custódia e gestão de recurso na Conta de Pagamento e licença de uso das Funcionalidades, o USUÁRIO pagará as Tarifas, fixas ou percentuais, incidentes sobre cada Transação realizada.</Text>
                                    <Text>8.2.	    O USUÁRIO pagará: (i) Tarifa por cada Transação realizada no Sistema Trucker Pay; (ii) Tarifa de saque dos recursos; e (iii) Tarifa por inatividade da Conta de Pagamento.</Text>
                                    <Text>8.2.1.	Além das Tarifas acima, haverá a cobrança de Tarifas adicionais, a depender da modalidade de Transação realizada pelo USUÁRIO, em razão do(a): (i) pagamento de boletos bancários (cujo valor poderá ser variável de acordo com o banco); (ii) emissão de boletos; (iii) transferência de recursos para a conta bancária cujo valor poderá ser variável de acordo com o banco); (iv) pagamentos instantâneos pelo Arranjo PIX; dentre outras que forem aplicáveis, conforme informado na Plataforma.</Text>
                                    <Text>8.2.2.	Também poderá ser realizada a cobrança de Tarifas adicionais para a realização de Transações Pós-Pagas e recebimento de pagamentos por estabelecimentos comerciais, de acordo com as condições previstas nos Anexos a este Termo.</Text>
                                    <Text>8.2.3.	Poderá ser estabelecido pacotes de serviços, mediante a cobrança de valores mensais, que concedem ao USUÁRIO o direito de realizar determinadas Transações no período.</Text>
                                    <Text>8.3.	    O valor das Tarifas é variável de acordo com a natureza de cada Transação, encontrando-se sempre disponíveis para consulta pelo USUÁRIO na Plataforma ou mediante solicitação por meio dos canais de atendimento disponíveis.</Text> 
                                    <Text>8.4.	    Para a cobrança das Tarifas, a Instituição de Pagamento irá: (i) realizar lançamentos de débitos na Conta de Pagamento; e (ii) compensar o valor dos débitos com quaisquer outros créditos, presentes ou futuros, do USUÁRIO.</Text>
                                    <Text>8.4.1.    Caso não haja recursos suficientes para o pagamento das Tarifas, será solicitado ao USUÁRIO o crédito imediato de recursos em sua Conta de Pagamento. Tão logo haja recursos na Conta de Pagamento, os valores serão debitados automaticamente e sem prévio aviso.</Text>
                                    <Text>8.4.2. 	Sem prejuízo da suspensão dos serviços prestados por meio do Sistema Trucker Pay, caso o USUÁRIO deixe de realizar o crédito em sua Conta de Pagamento, haverá a incidência dos encargos moratórios estipulados neste Termo.</Text>
                                    <Text>8.5.	    O valor das Tarifas cobradas poderá ser reajustado ou alterado, a qualquer momento, mediante comunicação ao USUÁRIO com antecedência de 10 (dez) dias.</Text>
                                    <Text>8.5.1.	Caso o USUÁRIO não concorde com as novas condições de remuneração, poderá encerrar este Termo, sem a incidência de quaisquer ônus ou penalidades. O não encerramento será interpretado como anuência com relação aos novos valores das Tarifas cobradas.</Text>
                                    <Text>8.6. 	    Caso sejam criados novos tributos ou alteradas as condições de cálculo e/ou cobrança de tributos incidentes sobre as Tarifas, haverá o reajuste dos valores cobrados de forma a restabelecer o equilíbrio econômico-financeiro.</Text>
                                    <Text>8.7.	    A MAN também poderá instituir outras modalidades de remuneração, mediante prévia comunicação ao USUÁRIO, com antecedência de 10 (dez) dias.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>9. 	Prazo de Vigência e Término</Text>
                                    <Text>9.1.	    Este Termo é celebrado por prazo indeterminado, e passa a vigorar a partir da data de sua aceitação pelo USUÁRIO.</Text>
                                    <Text>9.2.	    Este Termo será extinto, a qualquer momento e por qualquer das Partes, mediante notificação com antecedência de 30 (trinta) dia.</Text> 
                                    <Text>9.2.1.	Salvo quanto às hipóteses abaixo, a extinção deste Termo se dará sem a incidência de quaisquer ônus, encargos ou penalidades; ressalvadas as obrigações pendentes e que deverão ser devidamente cumpridas pelo prazo necessário.</Text>
                                    <Text>9.3.	    Haverá a rescisão imediata e motivada deste Termo, nas hipóteses de: (i) decretação de falência, pedido de recuperação judicial ou extrajudicial ou encerramento das atividades de qualquer das Partes, ao exclusivo critério da outra Parte; ou (ii) o descumprimento de qualquer obrigação estabelecida neste Termo que não seja sanada no prazo estipulado ou, na omissão, no prazo de 05 (cinco) dias contados da comunicação.</Text>
                                    <Text>9.4.	    Caso a rescisão do Termo ocorra por culpa do USUÁRIO, fica desde já estabelecido que seu acesso à Plataforma será imediatamente bloqueado, com a suspensão de sua Conta de Pagamento e retenção dos créditos do USUÁRIO pelo prazo necessário para que possam ser resguardados os direitos da MAN, da Instituição de Pagamento, do Banco Volkswagen, de outros USUÁRIOS e de terceiros; sem prejuízo da adoção de outras medidas legais necessárias.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>10. 	Responsabilidades Adicionais do USUÁRIO </Text>
                                    <Text>10.1.	    A realização de transferência bancária, emissão do boleto bancário, pagamentos instantâneos, dentre outras formas de realização das Transações, estarão sujeitos à cobrança de tarifas, taxas ou encargos específicos, cobrados adicionalmente às Tarifas decorrentes da realização das Transações, de acordo com os critérios e valores estabelecidos pelas instituições respectivas; sendo que a MAN não possui qualquer ingerência sobre os valores cobrados do USUÁRIO.</Text>
                                    <Text>10.2.	    O USUÁRIO reconhece e concorda que a realização das Transações pelo Sistema Trucker Pay está sujeita a aplicação da legislação vigente, inclusive de prevenção a lavagem de dinheiro, financiamento ao terrorismo e combate à corrupção; estando os repasses dos valores das Transações sujeitos ao estrito cumprimento da legislação aplicável.</Text>
                                    <Text>10.3.	    Para utilização das Funcionalidades e acesso ao Sistema Trucker Pay, o USUÁRIO deverá possuir equipamentos (computador, smartphone, tablet ou outros dispositivos similares) com acesso à internet e em condições compatíveis para seu uso, sendo de exclusiva responsabilidade do USUÁRIO a obtenção, manutenção e custeio de tal acesso e dos equipamentos necessários (incluindo tributos, tarifas ou encargos cobrados pelos fornecedores de serviços).</Text> 
                                    <Text>10.3.1.	A MAN e a Instituição de Pagamento não serão responsáveis pela não realização da Transação em razão da incompatibilidade dos equipamentos ou pela ausência ou falha no acesso à internet.</Text>
                                    <Text style={{fontWeight:'bold'}}>10.4.	    O USUÁRIO compromete-se a isentar a MAN e a Instituição de Pagamento de toda e qualquer reclamação ou litígio judicial ou extrajudicial decorrente da utilização do Sistema Trucker Pay, inclusive no que se refere às próprias atividades do USUÁRIO e às questões relacionadas com os negócios celebrados pelo USUÁRIO fora do Sistema Trucker Pay.</Text>
                                    <Text>10.5.	    O USUÁRIO obriga-se a ressarcir a MAN e a Instituição de Pagamento de todos os valores comprovadamente despendidos em ações judiciais ou processos administrativos que tenham sido ajuizados contra a MAN ou a Instituição de Pagamento em razão do descumprimento de obrigações imputáveis ao USUÁRIO.</Text>
                                    <Text>10.5.1.   A Instituição de Pagamento poderá reter os créditos a serem pagos ao USUÁRIO e compensá-los para o pagamento de débitos decorrentes de condenações, custas e despesas processuais, e honorários advocatícios.</Text>
                                    <Text>10.6.	    A MAN e a Instituição de Pagamento possuem uma Política de Privacidade que indica como as informações do USUÁRIO serão coletadas, utilizadas, armazenadas, tratadas, compartilhadas, divulgadas e protegidas. O USUÁRIO deve ler atentamente a Política de Privacidade, que é parte integrante deste Termo, e se encontra disponível para consulta na Plataforma.</Text>
                                    <Text>10.6.1.	A MAN e a Instituição de Pagamento irão adotar todas as medidas necessárias e se utilizar de tecnologias adequadas para proteger a coleta, processamento e armazenamento das informações do USUÁRIO; porém não têm como assegurar que terceiros não autorizados se utilizem de meios fraudulentos para furto, uso indevido, alteração ou acesso não autorizado às informações do USUÁRIO.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>11. 	Propriedade Intelectual </Text>
                                    <Text>11.1.	    A MAN, na qualidade de licenciada, autoriza o uso pelo USUÁRIO das Funcionalidades que integram o Sistema Trucker Pay, durante o prazo de vigência deste Termo.</Text>
                                    <Text>11.2.	    É vedado ao USUÁRIO: (i) copiar ou transferir de qualquer forma, total ou parcialmente, quaisquer Funcionalidades ou informações relativas às Funcionalidades; (ii) modificar as características das Funcionalidades ou realizar sua integração com outros sistemas ou softwares; (iii) copiar os dados extraídos do Sistema Trucker Pay, exceto aqueles relativos às movimentações da Conta de Pagamento.</Text>
                                    <Text>11.3.	    O USUÁRIO compromete-se a não infringir quaisquer direitos relativos às marcas, patentes, software, domínio na internet, segredo industrial ou, ainda, direito de propriedade industrial ou direito autoral de quaisquer serviços ou Funcionalidades, bem como a não usar o nome, marca, logomarca ou qualquer tipo de sinal distintivo da MAN ou do Banco Volkswagen, sem o consentimento prévio e escrito.</Text>
                                    <Text>11.4.	    Caso o USUÁRIO pretenda oferecer o Pix como forma de pagamento, deverá utilizar da marca Pix de acordo com as condições e limites estabelecidos pelo Banco Central do Brasil, declarando-se ciente de que:</Text>
                                    <Text>(a) 	A marca PIX é de titularidade exclusiva do Banco Central do Brasil e sua utilização deverá ser realizada em conformidade com os termos do regulamento Pix e do manual de uso relacionado com a marca;</Text>
                                    <Text>(b) 	Não deverá veicular a marca Pix em dimensão inferior às marcas, símbolos ou logotipos dos demais Instrumentos de Pagamento aceitos;</Text>
                                    <Text>(c) 	Não poderá transmitir a impressão de que o Pix possui aceitação mais restrita ou menos vantajosa perante outros Instrumentos de Pagamento aceitos;</Text>
                                    <Text>(d)	Não poderá: (i) reivindicar quaisquer direitos sobre a marca Pix; (ii) questionar a titularidade do Banco Central do Brasil sobre a marca Pix; (iii) registrar ou tentar registrar razão social, nome fantasia, logotipo ou qualquer nome de domínio de internet contendo referência à marca Pix; (iv) associar a marca Pix a quaisquer produtos não relacionados ao arranjo Pix; ou (v) utilizar a marca Pix além dos limites previstos no regulamento do Pix e respectivos manuais instituídos pelo Banco Central do Brasil;</Text>
                                    <Text>(e)	Não poderá utilizar a Marca Pix de modo a acarretar prejuízos ao Banco Central do Brasil ou ao arranjo Pix;</Text>
                                    <Text>(f)	Deverá comunicar à Instituição de Pagamento, imediatamente, pelos canais de atendimento indicados na Plataforma, sempre que tomar conhecimento do uso indevido, tentativa de cópia ou infração aos direitos decorrentes da marca Pix; e</Text>
                                    <Text>(g)	O uso da marca Pix não confere ao USUÁRIO qualquer direito de titularidade ou outro benefício referente à marca.</Text>
                                    <Text>11.5.	    Este Termo será rescindido, automaticamente e de pleno direito, em caso de infração quanto à violação das regras de uso da marca Pix.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>12.	Serviços Financeiros </Text>
                                    <Text>12.1.	    O USUÁRIO, conforme disponível, poderá contratar os Serviços Financeiros ofertados pelo Banco Volkswagen na Plataforma, mediante a utilização das Funcionalidades.</Text>
                                    <Text>12.1.1.	A abertura da Conta de Pagamento, em nenhuma hipótese, poderá ser considerada como a possibilidade de oferta e/ou contratação de Serviços Financeiros; cabendo ao Banco Volkswagen, a seu exclusivo critério, oferecer os Serviços Financeiros aos USUÁRIOS que entender conveniente.</Text>
                                    <Text>12.2.	    Com relação à oferta de Serviços Financeiros, a Instituição de Pagamento e a MAN são meras intermediadoras da relação entre o USUÁRIO e o Banco Volkswagen, uma vez que as Funcionalidades disponíveis na Plataforma têm a finalidade de apenas aproximar as partes, mediante a divulgação das condições preliminares para contratação</Text>
                                    <Text>12.2.1.   Para contratação dos Serviços Financeiros, o USUÁRIO poderá ou não ser direcionado ao site do Banco Volkswagen; que, inclusive, poderá solicitar novas informações, documentos e/ou dados relacionados ao USUÁRIO.</Text>
                                    <Text>12.2.2.   A efetiva contratação dos Serviços Financeiros se dará mediante a celebração de instrumento contratual próprio entre o USUÁRIO e o Banco Volkswagen, inclusive com relação a qualquer forma de financiamento das Faturas decorrentes das Transações Pós-Pagas.</Text>
                                    <Text>12.3.	    Por se tratar de uma atividade de intermediação, a MAN e a Instituição de Pagamento não possuem qualquer interferência nas condições, preços e execução dos Serviços Financeiros, inclusive sobre às condições de contratação, solicitação de documentos e demais atos pertinentes.</Text> 
                                    <Text>12.3.1.   A MAN e a Instituição de Pagamento não poderão, em nenhuma hipótese, ser responsabilizadas por quaisquer reclamações decorrentes da contratação dos Serviços Financeiros, cabendo ao USUÁRIO contatar diretamente o Banco Volkswagen sobre qualquer dúvida ou demanda.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>13. 	Disposições Gerais </Text>
                                    <Text>13.1.	    USUÁRIO declara-se ciente e concorda que, independentemente do local de onde esteja utilizando os serviços que integram o Sistema Trucker Pay, a relação entre as Partes será sempre regida pela legislação brasileira.</Text>
                                    <Text>13.2.	    O USUÁRIO expressamente autoriza a MAN a utilizar as informações, ainda que relativas ao seu Cadastro, Conta de Pagamento e Transações realizadas no Sistema Trucker Pay, para formação de banco de dados, preservando-se a individualidade e identificação de cada USUÁRIO.</Text>
                                    <Text>13.3.	    O USUÁRIO autoriza a Instituição de Pagamento e o Banco Volkswagen a verificar e trocar informações cadastrais, creditícias e/ou financeiras a seu respeito em âmbito nacional, com entidades financeiras ou de proteção ao crédito, inclusive a efetuar consultas a sistemas de risco de crédito, inclusive ao SCR do Banco Central do Brasil, sobre eventuais débitos de responsabilidades do USUÁRIO e a prestar ao órgão citado informações dos dados cadastrais e informações creditícias.</Text>
                                    <Text>13.3.1.	O USUÁRIO, por este Termo, autoriza expressamente o Banco Volkswagen a: (i) consultar e compartilhar com a Instituição de Pagamento, MAN e demais empresas de seu grupo econômico as informações obtidas junto ao Sistema de Informações de Crédito (“SCR”); (ii) registrar junto ao SCR as informações decorrentes deste Termo; e (iii) consultar os débitos e responsabilidades decorrentes de operações de crédito que constem ou venham a constar do SCR em nome do USUÁRIO, permanecendo válida a presente autorização durante a vigência deste Termo.</Text>
                                    <Text>13.3.2.	O SCR tem por finalidades: (i) fornecer informações ao Banco Central do Brasil para fins de supervisão do risco de crédito a que estão expostas as instituições financeiras e (ii) propiciar o intercâmbio, entre essas instituições, de informações sobre o montante de débitos e de responsabilidades de clientes em operações de crédito, com o objetivo de subsidiar decisões de crédito e de negócios.</Text> 
                                    <Text>13.3.3.	O USUÁRIO está ciente de que poderá obter quaisquer informações contidas no SCR diretamente perante o Banco Central do Brasil, pertinentes aos dados constantes em seu nome; sendo que pedidos de correções e exclusões e de manifestações de discordância deverão ser dirigidas diretamente às respectivas instituições financeiras que incluíram as informações no SCR.</Text>
                                    <Text>13.4.	    Nos termos da legislação aplicável e da Política de Privacidade, o USUÁRIO concorda que a MAN e o Banco Volkswagen enviem mensagens de caráter informativo ou publicitário.</Text>
                                    <Text>13.5.	    A Instituição de Pagamento irá auxiliar e cooperar com qualquer autoridade judicial, reguladora ou órgão público que venha a solicitar informações; podendo, neste caso, fornecer quaisquer informações e documentos do USUÁRIO.</Text>
                                    <Text>13.6.	    As Partes elegem o Foro da Cidade de São Paulo / SP como único competente para dirimir as questões decorrentes deste Termo, com renúncia expressa a qualquer outro, por mais privilegiado que seja.</Text>
                                    <Text>13.7.	    Qualquer dúvida em relação a este Termo poderá ser enviada à MAN, pelos e-mails contato@truckerpay.com.br ou suporte@truckerpay.com.br.</Text>
                                    <Text>Versão atualizada em 04 de maio de 2021.</Text>
                                    <Text style={{fontWeight:'bold'}}>MAN LATIN AMERICA INDÚSTRIA E COMÉRCIO DE VEÍCULOS LTDA</Text>
                                    <Text style={{fontWeight:'bold'}}>LOGIN TECNOLOGIA E PAGAMENTOS LTDA.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:10,textAlign:'center', textDecorationLine:'underline'}}>ANEXO I – TRANSAÇÕES PÓS-PAGAS</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:10,textAlign:'center'}}>TERMO DE ABERTURA DE CONTA DE PAGAMENTO</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:5,textAlign:'center'}}>SISTEMA TRUCKER PAY</Text> 
                                    <Text>Este Anexo I é parte integrante e inseparável do Termo de Abertura de Conta de Pagamento (“Termo”) e tem por objeto estabelecer as condições para a realização de Transações Pós-Pagas pelos USUÁRIOS, desde que previamente autorizados.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>1.	Definições </Text>
                                    <Text>1.1.	    Para o entendimento e interpretação deste Anexo I, entende-se por:</Text>
                                    <Text>“Fatura”: cobrança emitida ao USUÁRIO, para pagamento dos débitos contraídos em razão das Transações Pós-Pagas realizadas perante os Usuários Recebedores.</Text>
                                    <Text>“Limite de Crédito”: valor de crédito que poderá ser concedido ao USUÁRIO para a realização das Transações Pós-Pagas em determinado período.</Text>
                                    <Text>“Usuário Recebedor”: pessoa jurídica, credenciada ao Sistema Trucker Pay, que, em razão da comercialização de produtos e/ou serviços ao USUÁRIO, deverá receber o pagamento decorrente das Transações.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>2.	Transações Pós-Pagas </Text>
                                    <Text>2.1.	    Este Anexo I regula a prestação de serviços decorrentes do Sistema Trucker Pay, para que o USUÁRIO detentor de Conta de Pagamento, possa realizar Transações Pós-Pagas.</Text>
                                    <Text>2.2.	    A MAN e a Instituição de Pagamento, mediante oferta na Plataforma ou por solicitação do USUÁRIO, poderão permitir que o USUÁRIO realize Transações Pós-Pagas, concedendo um Limite de Crédito para sejam realizados pagamentos e transferências no Sistema Trucker Pay, mediante o pagamento posterior da Fatura.</Text>
                                    <Text>2.3.	    A possibilidade de realização de Transações Pós-Pagas depende da análise prévia pela MAN e pela Instituição de Pagamento, que poderão solicitar ao USUÁRIO o envio de informações e documentos adicionais aos solicitados no Cadastro.</Text>
                                    <Text>2.4.	    Sendo o USUÁRIO autorizado a realizar Transações Pós-Pagas, a Instituição de Pagamento realizará a gestão e custódia dos recursos aportados na Conta de Pagamento, mediante o envio da Fatura para pagamento posterior das Transações realizadas.</Text>
                                    <Text>2.5.	    Para a realização de Transações Pós-Pagas, serão cobradas Tarifas adicionais, além daquelas previstas no Termo, conforme informada no Cadastro e/ou na Plataforma.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>3.	Limite de Crédito </Text>
                                    <Text>3.1.	    Será disponibilizado ao USUÁRIO um Limite de Crédito, para que o pagamento das Transações Pós-Pagas seja realizado no prazo de vencimento da Fatura, conforme definido no momento do Cadastro.</Text>
                                    <Text>3.2. 	    O Limite de Crédito existente poderá ser reduzido, a qualquer tempo e mesmo que não haja solicitação pelo USUÁRIO: (i) mediante comunicação com 30 (trinta) dias de antecedência; ou (ii) imediatamente e independente de aviso prévio, caso seja constatado qualquer evento que possa ensejar na redução da capacidade financeira do USUÁRIO.</Text> 
                                    <Text style={{fontWeight:'bold', fontSize:16}}>4.	Pagamento da Fatura</Text>
                                    <Text>4.1.	    A Fatura será disponibilizada na Plataforma, com a descrição do(a): (i) valor de todas as Transações Pós-Pagas realizadas; (ii) data de vencimento da Fatura; (iii) valor das Tarifas aplicáveis; e (vi) valor do Limite de Crédito disponível.</Text>
                                    <Text>4.2. 	    A ausência de pagamento da Fatura, na data de vencimento, ensejará na cobrança de juros moratórios de 1% (um por cento) ao mês; multa de 2% (dois por cento) e correção monetária pelo IGPM/FGV – ou outro índice que vier a substituí-lo -, incidentes sobre o valor inadimplido.</Text> 
                                    <Text>4.3.	    Em caso de inadimplemento da Fatura, o Banco Volkswagen realizará o pagamento em favor do USUÁRIO, mediante crédito na Conta de Pagamento; para que a Instituição de Pagamento possa realizar a liquidação das Transações aos Usuários Recebedores</Text>
                                    <Text>4.3.1.	Com o pagamento da Fatura, na forma acima indicada, o Banco Volkswagen fica automaticamente sub-rogado em todos os direitos sobre o crédito representado na Fatura; tornando-se credor do USUÁRIO no valor devido, acrescido dos encargos moratórios indicados.</Text>
                                    <Text>4.4.	    O USUÁRIO reconhece que, nos termos do artigo 784, inciso III, do Código de Processo Civil, os valores das Transações Pós-Pagas lançadas na Fatura constituem dívida líquida, certa e exigível; e que o Termo, juntamente com o extrato da movimentação da Conta de Pagamento, constitui título executivo extrajudicial.</Text> 
                                    <Text>4.5.	    Em caso de inadimplemento do USUÁRIO quanto ao pagamento da Fatura, a MAN e a Instituição de Pagamento poderão, sem a necessidade de aviso prévio ou qualquer outra formalidade, bloquear o acesso à Plataforma e suspender a realização de novas Transações Pós-Pagas, até a liquidação do valor inadimplido, acrescido dos encargos moratórios incidentes.</Text>
                                    <Text>4.6.	    O USUÁRIO desde já autoriza a MAN e a Instituição de Pagamento, nos termos previstos na Política de Privacidade, a compartilhar os seus dados cadastrais, financeiros e pessoais com o Banco Volkswagen, para possibilitar a definição do Limite de Crédito a ser concedido ao USUÁRIO.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>5.	Disposições Gerais</Text>
                                    <Text>Versão atualizada em 04 de maio de 2021.</Text>
                                    <Text style={{fontWeight:'bold'}}>MAN LATIN AMERICA INDÚSTRIA E COMÉRCIO DE VEÍCULOS LTDA</Text>
                                    <Text style={{fontWeight:'bold'}}>LOGIN TECNOLOGIA E PAGAMENTOS LTDA.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:10,textAlign:'center', textDecorationLine:'underline'}}>ANEXO II – CREDENCIAMENTO DE ESTABELECIMENTOS</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:10,textAlign:'center'}}>TERMO DE ABERTURA DE CONTA DE PAGAMENTO </Text>
                                    <Text style={{fontWeight:'bold', fontSize:16, marginTop:5,textAlign:'center'}}>SISTEMA TRUCKER PAY</Text>
                                    <Text>Este Anexo II é parte integrante e inseparável do Termo de Abertura de Conta de Pagamento (“Termo”) e tem por objeto estabelecer as condições para o credenciamento do USUÁRIO, que, na qualidade de Estabelecimento, pretenda receber pagamentos em razão da comercialização de produtos e/ou serviços.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>1.	Definições</Text>
                                    <Text>1.1.	Para o entendimento e interpretação deste Anexo II, entende-se por:</Text>
                                    <Text>“Comprador”: USUÁRIO que, por meio do Sistema Trucker Pay, realiza o pagamento em razão da compra bens e/ou serviços comercializados pelo Estabelecimento.</Text>
                                    <Text>“Estabelecimento”: pessoa jurídica ou física, fornecedora de bens e/ou serviços, constituída e localizada dentro do território brasileiro, que será credenciada ao Sistema Trucker Pay para receber pagamentos decorrentes da Transações realizadas pelos Compradores.</Text> 
                                    <Text>“Serviços”: serviços de captura, processamento e liquidação das Transações, que serão prestados ao Estabelecimento em razão deste Anexo II.</Text>
                                    <Text>“Tarifa por Transação”: remuneração a ser paga pelo Estabelecimento à Instituição de Pagamento, incidente sobre o valor bruto da Transação, em razão dos Serviços.</Text>
                                    <Text>“Valor Líquido”: valor a ser pago ao Estabelecimento em razão das Transações realizadas pelos Compradores, após a dedução da Tarifa por Transação, e das demais Tarifas que forem devidas em razão do Termo.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>2.	Credenciamento do Estabelecimento</Text>
                                    <Text>2.1.	    O objeto deste Anexo II é o credenciamento do Estabelecimento ao Sistema Trucker Pay, para a prestação dos seguintes Serviços:</Text>
                                    <Text>(a)   Habilitação do Estabelecimento para aceitar pagamentos por meio do Sistema Trucker Pay, de acordo com as regras prevista no Termo e neste Anexo II; e</Text> 
                                    <Text>(b)	Gestão e coordenação de pagamentos ao Estabelecimento que sejam decorrentes de Transações realizadas no Sistema Trucker Pay.</Text>
                                    <Text>2.2.	    O credenciamento do Estabelecimento depende da análise prévia pela MAN e pela Instituição de Pagamento, que poderão solicitar ao Estabelecimento o envio de informações e documentos adicionais aos solicitados no Cadastro</Text>
                                    <Text>2.3.	    O Estabelecimento não poderá efetuar Transações ou atividades consideradas ilegais, contrárias às leis vigentes ou às normas do Banco Central do Brasil.</Text>
                                    <Text>2.3.1.	O Estabelecimento deverá manter todos os seus dados atualizados; comprometendo-se a encaminhar os documentos que comprovem as alterações, sempre que solicitado.</Text> 
                                    <Text>2.3.2.	O Estabelecimento autoriza a MAN a fiscalizar e vistoriar suas dependências durante o horário comercial, diretamente ou por terceiros autorizados, sempre que for necessário para averiguar o cumprimento das obrigações previstas neste Anexo II.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>3.	Serviços</Text>
                                    <Text>3.1.	    Os Serviços serão prestados de forma remota, mediante a disponibilização das tecnologias que integram o Sistema Trucker Pay, para que o Estabelecimento possa realizar a venda de seus produtos e/ou serviços, e que incluem:</Text>
                                    <Text>(a) 	A captura, o processamento e a concretização das Transações realizadas pelos Compradores por meio do Sistema Trucker Pay; e</Text>
                                    <Text>(b) 	A liquidação do Valor Líquido das Transações, após desconto da Tarifa por Transação e das demais Tarifas devidas em razão do Termo.</Text>
                                    <Text>3.2.	    O Estabelecimento não poderá se utilizar dos Serviços para atividades relacionadas, direta ou indiretamente, com fraudes a instituições financeiras, a outras instituições de pagamento, a qualquer terceiro ou ainda a qualquer pessoa jurídica que, alguma forma, se relacione com o sistema de pagamentos brasileiro.</Text>
                                    <Text>3.2.1.	A Instituição de Pagamento poderá não processar ou cancelar uma Transação por regras próprias de segurança, inclusive em razão do volume médio de Transações realizadas pelo Estabelecimento, ou com base nas informações cadastrais dos Compradores.</Text>
                                    <Text>3.3.	    O Estabelecimento deverá utilizar o Sistema Trucker Pay somente para realizar Transações regulares, sendo vedada a realização de Transações fictícias ou simuladas.</Text>
                                    <Text>3.3.1.	Também são vedadas Transações: (i) em segmentos ou ramos de atividade diferentes daquele(s) constante(s) de seu Cadastro, ainda que constem de seu objeto social; (ii) cujo objeto envolva bens e/ou serviços proibidos pela legislação vigente ou autoridades governamentais ou órgãos reguladores; (iii) que o Estabelecimento saiba ou deva saber estar o Comprador impedido de realizar; (iv) que visem a refinanciar dívidas dos Compradores; (v) que condicionem a Transação à revelação da senha pessoal e intransferível dos Compradores; (vi) por meio do desmembramento do preço de um mesmo bem ou serviço em mais de uma Transação; ou (vii) em moeda estrangeira; dentre outras que não sejam permitidas pela legislação vigente</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>4.	Pagamento das Transações</Text>
                                    <Text>4.1.	    A Instituição de Pagamento efetuará o pagamento das Transações realizadas no Sistema Trucker Pay, mediante repasse do respectivo Valor Líquido para a Conta de Pagamento de titularidade do Estabelecimento.</Text>
                                    <Text>4.2.	    O pagamento será realizado pelo Valor Líquido, após descontada a Tarifa por Transação devida à Instituição de Pagamento, assim como as demais Tarifas previstas no Termo, conforme aplicáveis.</Text> 
                                    <Text>4.3.	    O Valor Líquido da Transação será pago ao Estabelecimento em 30 (trinta) dias contados da sua realização pelo Comprador.</Text>
                                    <Text>4.4.	    O Estabelecimento poderá solicitar o pagamento antecipado da Transação, mediante solicitação na Plataforma, para que o Valor Líquido seja pago em 02 (dois) dias úteis contados da solicitação.</Text>
                                    <Text>4.4.1.	O pagamento antecipado ensejará: (i) na cobrança de Tarifa por Transação em valor adicional; e (ii) na cobrança imediata da Transação perante os respectivos Compradores.</Text>
                                    <Text>4.5.	    Se o Estabelecimento deixar de cumprir com suas obrigações constantes do Termo ou deste Anexo II, ainda que a Transação tenha sido aprovada pela Instituição de Pagamento, o valor da Transação não será repassado ou, se já tiver sido repassado, ficará sujeito a estorno.</Text> 
                                    <Text>4.5.1.	A regra acima também será aplicada nas seguintes situações: (i) se a Transação for cancelada pelo Estabelecimento, mediante solicitação na Plataforma; (ii) se as informações relativas à Transação forem incompletas, imprecisas ou inverídicas; (iii) se for constatado que as Transações, em razão de suas características, expõem a risco os Compradores, a MAN e/ou a Instituição de Pagamento; (iv) se a Transação não for comprovada; (v) se houver ordem de autoridade legítima impedindo o repasse ou determinando o bloqueio, penhora, arresto, custódia ou depósito dos créditos em conta que não a Conta de Pagamento do Estabelecimento; (vi) se houver erro no processo de aprovação da Transação ou a aprovação for negada; (vii) se o Estabelecimento alterar quaisquer dados da Transação após aprovação pela Instituição de Pagamento; (viii) se houver indícios de fraude ou ilicitude na Transação; (ix) se o Estabelecimento realizar Transação suspeita ou irregular; ou (x) se a Instituição de Pagamento for envolvida em qualquer medida judicial relativamente à Transação, sem que o Estabelecimento tome as providências necessárias para exclusão da Instituição de Pagamento da lide.</Text>
                                    <Text>4.5.2.	Não será possível o pagamento antecipado das Transações que forem objeto de pedido de abertura de Disputa, de acordo com as condições previstas no Termo.</Text>
                                    <Text>4.6.	    Com o crédito dos recursos da Conta de Pagamento, o Estabelecimento poderá realizar pagamentos e transferências, de acordo com as modalidades previstas no Termo, inclusive o resgate de recursos.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>5.	Tarifa por Transação</Text>
                                    <Text>5.1.	    Em contrapartida à prestação dos Serviços, o Estabelecimento pagará à Instituição de Pagamento a Tarifa por Transação, incidente sobre o valor bruto de cada Transação realizada no Sistema Trucker Pay.</Text> 
                                    <Text>5.1.1.	A Tarifa por Transação poderá variar conforme o segmento ou ramo de atuação do Estabelecimento, sua localização, forma de captura da Transação, entre outros critérios adotados.</Text>
                                    <Text>5.1.2.	Ainda, o valor da Tarifa por Transação será variável de acordo com a data de pagamento, inclusive caso o Estabelecimento solicite sua antecipação.</Text>
                                    <Text>5.2.	    O valor da Tarifa por Transação e demais Tarifas previstas no Termo (conforme aplicáveis) serão automaticamente descontados, antes do pagamento do Valor Líquido das Transações.</Text>
                                    <Text style={{fontWeight:'bold', fontSize:16}}>6.	Disposições Gerais</Text>
                                    <Text>6.1.	    Aplicam-se subsidiariamente a este Anexo II todas as obrigações e responsabilidades do Estabelecimento, na condição de USUÁRIO, que se encontram previstas no Termo, inclusive as definições.</Text>
                                    <Text>6.2.	    O prazo de vigência deste Anexo II será equivalente ao prazo de vigência do Termo; podendo qualquer das Partes optar pela manutenção do Termo e resilir este Anexo II, a qualquer tempo e sem motivação, mediante comunicação por escrito, com 30 (trinta) dias de antecedência</Text>
                                    <Text>6.3.	    Os termos e condições previstas neste Anexo II poderão ser alterados pelas mesmas formas previstas no Termo.</Text>
                                    <Text>Versão atualizada em 04 de maio de 2021.</Text>
                                    <Text style={{fontWeight:'bold'}}>MAN LATIN AMERICA INDÚSTRIA E COMÉRCIO DE VEÍCULOS LTDA</Text>
                                    <Text style={{fontWeight:'bold'}}>LOGIN TECNOLOGIA E PAGAMENTOS LTDA.</Text>





                                
                            </ScrollView>

                            <View>
                                <TouchableOpacity style={{marginBottom:30}} onPress={()=> navigation.navigate("Login")} >
                                    <Text style={{textDecorationLine:'underline', color:'#011e50', fontSize:18}}> Voltar </Text>
                                </TouchableOpacity>
                            </View>

                </View>
            </View>
        );
    }


const style = StyleSheet.create({
    container:{
        backgroundColor: '#fff',
        flex:1
      },
      body:{
        backgroundColor: '#fff',
        flex:4,
        alignItems: 'center'
      },
      input:{
        borderBottomColor: '#707070',
        borderBottomWidth: 1,
        width: '90%',
        marginTop: '15%',
        fontSize:18

      },
      btn:{
        backgroundColor:'#4FA2DA',
        justifyContent:'center',
        alignItems:'center',
        width: 150,
        height: 40,
        borderRadius:10
    }, 
})
